import os

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_SERVER = os.getenv("POSTGRES_SERVER")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DB = os.getenv("POSTGRES_DB")

AUTHORIZATION_SERVER_KEY = os.getenv("AUTHORIZATION_SERVER_KEY")
SERVER_TYPE = os.getenv("SERVER_TYPE")